import React,{useEffect,useState}from"react";
import{View,Text,StyleSheet,Pressable,TextInput,ActivityIndicator,ScrollView,Alert}from"react-native";
import{useRouter}from"expo-router";import{Ionicons}from"@expo/vector-icons";import{useSafeAreaInsets}from"react-native-safe-area-context";
import{useAuth,AccessUser}from"@/src/context/AuthContext";import{colors,spacing,radius,font}from"@/src/theme";import{VLogo}from"@/src/components/ui";
const labels:any={patient:"Patient",doctor:"Arzt / Ärztin",caregiver:"Pflegefachkraft",relative:"Angehörige/r"};
export default function Login(){const{user,accessUser,accessUsers,loading,signingIn,login,loginWithPin}=useAuth();const[sel,setSel]=useState<AccessUser|null>(null),[pin,setPin]=useState(""),[busy,setBusy]=useState(false);const r=useRouter(),i=useSafeAreaInsets();
useEffect(()=>{if(!loading&&!user)login().catch(()=>Alert.alert("Fehler","Server nicht erreichbar."));},[loading,user]);useEffect(()=>{if(accessUser)r.replace("/(tabs)");},[accessUser]);
const go=async()=>{if(!sel||pin.length<4)return;setBusy(true);try{await loginWithPin(sel,pin);r.replace("/(tabs)");}catch{Alert.alert("Falsche PIN","Bitte PIN erneut eingeben.");setPin("");}finally{setBusy(false)}};
return <View style={[s.c,{paddingTop:i.top+24,paddingBottom:i.bottom+20}]}><VLogo size={68}/><Text style={s.brand}>VYLNAX <Text style={{color:"#4DA6E8"}}>PRO</Text></Text><Text style={s.h}>Wer meldet sich an?</Text>{signingIn||loading?<ActivityIndicator color="#fff" size="large"/>:<><ScrollView style={{width:"100%"}} contentContainerStyle={{gap:10}}>{accessUsers.map(p=><Pressable key={p.id} onPress={()=>{setSel(p);setPin("")}} style={[s.profile,sel?.id===p.id&&s.active]}><Ionicons name={p.role==="patient"?"person":p.role==="relative"?"people":p.role==="doctor"?"medical":"medkit"} size={24} color={sel?.id===p.id?"#fff":"#4DA6E8"}/><View style={{flex:1}}><Text style={s.name}>{p.name}</Text><Text style={s.role}>{labels[p.role]}</Text></View></Pressable>)}</ScrollView>{sel&&<View style={s.pinBox}><Text style={s.pinLabel}>PIN für {sel.name}</Text><TextInput value={pin} onChangeText={setPin} keyboardType="number-pad" secureTextEntry maxLength={4} autoFocus style={s.pin} placeholder="••••" placeholderTextColor="#7C93A8"/><Pressable onPress={go} disabled={busy||pin.length!==4} style={[s.btn,(busy||pin.length!==4)&&{opacity:.5}]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.bt}>Anmelden</Text>}</Pressable></View>}</>}</View>}
const s=StyleSheet.create({c:{flex:1,backgroundColor:"#0A1929",alignItems:"center",paddingHorizontal:20},brand:{color:"#fff",fontSize:25,fontWeight:"900",marginTop:10},h:{color:"#fff",fontSize:25,fontWeight:"800",alignSelf:"flex-start",marginVertical:24},profile:{width:"100%",backgroundColor:"#112B43",borderWidth:1,borderColor:"#24445F",borderRadius:14,padding:15,flexDirection:"row",alignItems:"center",gap:14},active:{backgroundColor:"#1A65A9",borderColor:"#4DA6E8"},name:{color:"#fff",fontSize:17,fontWeight:"800"},role:{color:"#B9CCE0",marginTop:2},pinBox:{width:"100%",marginTop:18},pinLabel:{color:"#DCE9F5",fontWeight:"700",marginBottom:8},pin:{height:58,backgroundColor:"#fff",borderRadius:12,textAlign:"center",fontSize:28,letterSpacing:12,color:"#12263A"},btn:{height:54,borderRadius:12,backgroundColor:"#1A65A9",alignItems:"center",justifyContent:"center",marginTop:12},bt:{color:"#fff",fontSize:17,fontWeight:"800"}})
