import React,{useCallback,useState} from "react";
import {View,Text,StyleSheet,ScrollView,Pressable,Switch,TextInput,Alert,ActivityIndicator} from "react-native";
import {Ionicons} from "@expo/vector-icons";
import {useRouter,useFocusEffect} from "expo-router";
import {useSafeAreaInsets} from "react-native-safe-area-context";
import {api} from "@/src/api";
import {useApp} from "@/src/context/AppContext";
import {useAuth} from "@/src/context/AuthContext";
import {colors,spacing,radius} from "@/src/theme";
import {Card,PrimaryButton} from "@/src/components/ui";

const fields=[
 ["first_reminder_minutes","1. Erinnerung nach","Min."],
 ["second_reminder_minutes","2. Erinnerung nach","Min."],
 ["notify_relative_minutes","Angehörige informieren nach","Min."],
 ["notify_caregiver_minutes","PFK informieren nach","Min."],
] as const;
export default function Reminders(){
 const router=useRouter(),ins=useSafeAreaInsets(); const {activePatient}=useApp(); const {canEditMedications}=useAuth();
 const [data,setData]=useState<any>(null),[settings,setSettings]=useState<any>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{if(!activePatient)return;setLoading(true);try{const [c,s]=await Promise.all([api(`/patients/${activePatient.id}/reminder-center`),api(`/patients/${activePatient.id}/reminder-settings`)]);setData(c);setSettings(s)}catch(e:any){Alert.alert("Fehler",e.message||"Daten konnten nicht geladen werden")}finally{setLoading(false)}},[activePatient]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 const save=async()=>{if(!activePatient||!settings)return;setSaving(true);try{await api(`/patients/${activePatient.id}/reminder-settings`,{method:"PUT",access:true,body:settings});Alert.alert("Gespeichert","Erinnerungen wurden aktualisiert.");await load()}catch(e:any){Alert.alert("Fehler",e.message||"Speichern nicht möglich")}finally{setSaving(false)}};
 return <View style={s.c}><View style={[s.h,{paddingTop:ins.top+8}]}><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={25}/></Pressable><View><Text style={s.title}>Erinnerungszentrale</Text><Text style={s.sub}>{activePatient?.name}</Text></View><Pressable onPress={load}><Ionicons name="refresh" size={23} color={colors.brandPrimary}/></Pressable></View>
 <ScrollView contentContainerStyle={{padding:spacing.lg,paddingBottom:80}}>{loading?<ActivityIndicator color={colors.brandPrimary} style={{marginTop:60}}/>:<>
 <View style={s.stats}><Stat n={data?.counts?.taken||0} l="Bestätigt" icon="checkmark-circle"/><Stat n={data?.counts?.missed||0} l="Überfällig" icon="time"/><Stat n={data?.counts?.escalated||0} l="Eskaliert" icon="notifications"/></View>
 <Text style={s.section}>Aktuelle Hinweise</Text>{!data?.alerts?.length?<Card><Text style={s.ok}>✓ Keine überfälligen Einnahmen.</Text></Card>:data.alerts.map((a:any)=><Card key={a.id} style={s.alert}><View style={s.row}><Ionicons name={a.stage==="caregiver"||a.stage==="relative"?"alert-circle":"notifications"} size={24} color={a.stage==="caregiver"?colors.error:colors.warning}/><View style={{flex:1}}><Text style={s.med}>{a.name} · {a.dosage}</Text><Text style={s.msg}>{a.message}</Text><Text style={s.meta}>{a.scheduled_time} · {a.delay_minutes} Min. überfällig · Empfänger: {a.recipient}</Text></View></View></Card>)}
 <Text style={s.section}>Eskalationsregeln</Text><Card><View style={s.toggle}><View><Text style={s.label}>Erinnerungen aktiv</Text><Text style={s.help}>Personalisierte Medikamentenhinweise</Text></View><Switch value={!!settings?.enabled} onValueChange={v=>setSettings({...settings,enabled:v})} disabled={!canEditMedications}/></View><View style={s.toggle}><View><Text style={s.label}>Sprachausgabe</Text><Text style={s.help}>VYLNAX spricht die Erinnerung</Text></View><Switch value={!!settings?.voice_enabled} onValueChange={v=>setSettings({...settings,voice_enabled:v})} disabled={!canEditMedications}/></View>{fields.map(([k,l,u])=><View key={k} style={s.field}><Text style={s.label}>{l}</Text><View style={s.num}><TextInput keyboardType="number-pad" value={String(settings?.[k]??"")} onChangeText={v=>setSettings({...settings,[k]:Number(v.replace(/\D/g,""))||0})} editable={canEditMedications} style={s.input}/><Text>{u}</Text></View></View>)}{canEditMedications?<PrimaryButton label="Regeln speichern" icon="save" loading={saving} onPress={save} style={{marginTop:16}}/>:<Text style={s.readonly}>Nur Arzt oder PFK können Regeln ändern.</Text>}</Card>
 <Card style={{marginTop:16}}><Text style={s.note}>Hinweis: Diese Version berechnet Eskalationen im Backend. Echte Push-Nachrichten, SMS oder Anrufe benötigen später einen Benachrichtigungsdienst und bestätigte Kontaktdaten.</Text></Card>
 </>}</ScrollView></View>}
function Stat({n,l,icon}:any){return <Card style={s.stat}><Ionicons name={icon} size={22} color={colors.brandPrimary}/><Text style={s.n}>{n}</Text><Text style={s.sl}>{l}</Text></Card>}
const s=StyleSheet.create({c:{flex:1,backgroundColor:colors.surfaceSecondary},h:{backgroundColor:colors.surface,paddingHorizontal:spacing.lg,paddingBottom:12,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1,borderBottomColor:colors.border},title:{fontSize:20,fontWeight:"800",textAlign:"center"},sub:{fontSize:12,color:colors.onSurfaceTertiary,textAlign:"center"},stats:{flexDirection:"row",gap:8},stat:{flex:1,alignItems:"center",padding:12},n:{fontSize:22,fontWeight:"800",marginTop:4},sl:{fontSize:11,color:colors.onSurfaceTertiary},section:{fontSize:17,fontWeight:"800",marginTop:22,marginBottom:10},alert:{marginBottom:10,borderLeftWidth:4,borderLeftColor:colors.warning},row:{flexDirection:"row",gap:12},med:{fontWeight:"800",fontSize:15},msg:{marginTop:4,color:colors.onSurfaceSecondary},meta:{fontSize:11,color:colors.onSurfaceTertiary,marginTop:6},ok:{fontWeight:"700",color:colors.success},toggle:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingVertical:10,borderBottomWidth:1,borderBottomColor:colors.border},label:{fontWeight:"700"},help:{fontSize:12,color:colors.onSurfaceTertiary,marginTop:2},field:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingVertical:10,borderBottomWidth:1,borderBottomColor:colors.border},num:{flexDirection:"row",alignItems:"center",gap:8},input:{width:58,borderWidth:1,borderColor:colors.border,borderRadius:radius.sm,padding:8,textAlign:"center",backgroundColor:colors.surface},readonly:{marginTop:14,color:colors.onSurfaceTertiary,textAlign:"center"},note:{fontSize:12,color:colors.onSurfaceSecondary,lineHeight:18}})
