import React,{useCallback,useState} from "react";
import {View,Text,StyleSheet,ScrollView,ActivityIndicator,Pressable} from "react-native";
import {Ionicons} from "@expo/vector-icons";
import {router,useFocusEffect} from "expo-router";
import {useSafeAreaInsets} from "react-native-safe-area-context";
import {api} from "@/src/api"; import {useApp} from "@/src/context/AppContext"; import {colors,spacing,radius} from "@/src/theme"; import {Card} from "@/src/components/ui";
export default function WeeklyIntelligence(){const {activePatient}=useApp();const ins=useSafeAreaInsets();const [d,setD]=useState<any>();const [loading,setLoading]=useState(true);const load=useCallback(async()=>{if(!activePatient)return;setLoading(true);try{setD(await api(`/patients/${activePatient.id}/weekly-intelligence?days=7`));}finally{setLoading(false)}},[activePatient]);useFocusEffect(useCallback(()=>{load()},[load]));
return <View style={s.c}><View style={[s.h,{paddingTop:ins.top+8}]}><Pressable onPress={()=>router.back()}><Ionicons name="chevron-back" size={28}/></Pressable><Text style={s.ht}>KI-Wochenanalyse</Text><View style={{width:28}}/></View><ScrollView contentContainerStyle={{padding:18,paddingBottom:80}}>{loading?<ActivityIndicator/>:d?<><Card><Text style={s.name}>{activePatient?.name}</Text><Text style={s.big}>{d.risk_score}</Text><Text style={[s.level,{color:d.risk_level==='hoch'?colors.error:d.risk_level==='mittel'?colors.warning:colors.success}]}>Risiko: {d.risk_level}</Text><Text style={s.p}>{d.narrative}</Text></Card><View style={s.row}><Mini n={`${d.adherence}%`} l="Einnahmequote"/><Mini n={d.missed} l="Versäumt"/><Mini n={d.vital_alerts} l="Vital-Hinweise"/></View><Title t="Erkannte Signale"/>{d.reasons.map((x:string,i:number)=><Card key={i} style={s.item}><Ionicons name="analytics" size={18} color={colors.brandPrimary}/><Text style={s.flex}>{x}</Text></Card>)}<Title t="Empfehlungen"/>{d.recommendations.map((x:string,i:number)=><Card key={i} style={s.item}><Ionicons name="checkmark-circle" size={18} color={colors.success}/><Text style={s.flex}>{x}</Text></Card>)}<Text style={s.dis}>{d.disclaimer}</Text></>:<Text>Keine Daten</Text>}</ScrollView></View>}
function Mini({n,l}:any){return <Card style={s.mini}><Text style={s.mn}>{n}</Text><Text style={s.ml}>{l}</Text></Card>}function Title({t}:any){return <Text style={s.title}>{t}</Text>}
const s=StyleSheet.create({c:{flex:1,backgroundColor:colors.surfaceSecondary},h:{backgroundColor:'#fff',paddingHorizontal:16,paddingBottom:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderColor:colors.border},ht:{fontSize:20,fontWeight:'800'},name:{fontSize:18,fontWeight:'800'},big:{fontSize:52,fontWeight:'900',color:colors.brandPrimary,marginTop:8},level:{fontSize:18,fontWeight:'800'},p:{marginTop:10,lineHeight:21,color:colors.onSurfaceSecondary},row:{flexDirection:'row',gap:8,marginTop:12},mini:{flex:1,alignItems:'center',paddingHorizontal:6},mn:{fontSize:22,fontWeight:'900'},ml:{fontSize:11,textAlign:'center',color:colors.onSurfaceTertiary},title:{fontSize:18,fontWeight:'900',marginTop:22,marginBottom:10},item:{flexDirection:'row',gap:10,alignItems:'center',marginBottom:8},flex:{flex:1,lineHeight:20},dis:{fontSize:11,color:colors.onSurfaceTertiary,lineHeight:17,marginTop:18}})
